### ISSUE TITLE
Can not active bluetooth

### ISSUE THREAD

**Issue by skull141209** [revunix/ThinkCentre-M720Q#1]
Hi, really appreciate your work
I applied it to my system and it works perfectly except for the Bluetooth on the bcm94360cs2 card

Can you please have a fix at it

Thank you

**Comment by revunix** [comment]
There is a fix. Replace the USBMap.kext with usbinjectall.kext and enter this in the config.plist. After that it will work. I will update the repo later.

**Comment by skull141209** [comment]
LoL. I got the Apple Logo freeze

**Comment by skull141209** [comment]
> There is a fix. Replace the USBMap.kext with usbinjectall.kext and enter this in the config.plist. After that it will work. I will update the repo later.

But anyway thanks, I’m finding a way

**Comment by revunix** [comment]
> LoL. I got the Apple Logo freeze

Did you remove the USBMaps part from the config.plist?

**Comment by skull141209** [comment]
I manage it to work now, but without USBMAP.kext that you built, I can not use the front I/O. I'm trying to figure it out myself now. If you use telegram, please add @pshyduc I hope I'll get some help from you. 
Great EFI man

**Comment by skull141209** [comment]
It's work perfectly now. I think you can close this issue now
