### ISSUE TITLE
macOS Ventura EFI

### ISSUE THREAD

**Issue by siyu99fly** [revunix/ThinkCentre-M720Q#12]
Thank you very much for whether the MacOS Ventura 13 God can provide a Lenovo m720q efi

**Comment by revunix** [comment]
I updated OpenCore and all kexts. Give me feedback. I don't have this device anymore, so I can't test.

[Release 1.3-beta.zip](https://github.com/revunix/ThinkCentre-M720Q/files/9869316/Release.1.3-beta.zip)
