### ISSUE TITLE
help

### ISSUE THREAD

**Issue by siyu99fly** [revunix/ThinkCentre-M720Q#7]
Can you help write an m720q EFI based on OpenCORE 0.79 and Monterey 12.3.1 system. thank you

**Comment by revunix** [comment]
Is there a problem with macOS 12.3.1 ?

**Comment by siyu99fly** [comment]
Use BCM94360CS2 to network stutter on macOS 12.3.1

**Comment by revunix** [comment]
> Use BCM94360CS2 to network stutter on macOS 12.3.1

But this has nothing to do with my OC config. Normally, BCM94360CS2 works OOB.
You can try to disable the USB kext. Maybe it works after disabling better.
