### ISSUE TITLE
Lan

### ISSUE THREAD

**Issue by Flol0** [revunix/ThinkCentre-M720Q#9]
Hi i don't get LAN to work with this OpenCore config. Is this known?

**Comment by revunix** [comment]
Hey, there is no problem with Ethernet. But please try to set a custom DNS like 1.1.1.1, 1.0.0.1 in the network settings.

**Comment by Flol0** [comment]
Hi in ifconfig i don't find the lan adapter. Its flashing though

**Comment by revunix** [comment]
Ah okay, then your model has an Intel LAN Adapter. Add IntelMausi to your config.

**Comment by Flol0** [comment]
Thank you very much. I will try it out.

Since it is no issue with your Config then, you can close the issue. 

And a sorry for not realizing i have an Intel NIC

**Comment by Flol0** [comment]
It's working perfectly fine now! Thanks for the hint!
